name: Deploy a Surge.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar surge
      run: npm install --global surge

    - name: Desplegar en surge.sh
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        SURGE_DOMAIN: ${{ secrets.SURGE_DOMAIN }}
      run: |
        surge ./ --token $SURGE_TOKEN --domain $SURGE_DOMAIN
nches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar surge
      run: npm install --global surge

    - name: Desplegar en surge.sh
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        SURGE_DOMAIN: ${{ secrets.SURGE_DOMAIN }}
      run: |
        surge ./ --token $SURGE_TOKEN --domain $SURGE_DOMAIN


